### ISSUE TITLE
Bug: Incorrect addition of H1 when the note only contains front-matter

### ISSUE THREAD

**Issue by alexfertel** [platers/obsidian-linter#513]
## Describe the Bug

I had a note that only consisted of YAML front-matter. I activated the linter option "Inserts the file name as an H1 if no H1 exists.". When you lint the file, the heading gets added after the closing `---` of the front-matter and a blank line gets inserted after the opening `---`.

## How to Reproduce

1. Create a new note with an arbitrary title.
2. Add a frontmatter block to it.
3. Make sure there is no new-line at the end of the file.
4. Go to the linter options and activate "Inserts the file name as an H1 if no H1 exists." in the heading options.
5. Lint the note.

Example to reproduce issue with

Say we have a note with title `Test note` which has the following contents:

``` markdown
---
hello: test
---
```

Note: there is no ending new-line after the closing `---`.

After a lint, the note gets converted to:

```markdown
---

hello: test
---# Test note
```

## Expected Behavior

The note gets properly linted, and the title of the note gets added below the YAML front-matter.

``` markdown
---
hello: test
---

# Test note
```

## Screenshots

<img width="711" alt="Screenshot 2022-11-25 at 14 50 59" src="https://user-images.githubusercontent.com/22298999/203989698-c9d406ea-14a4-49d0-b6c3-30668af4f9ff.png">
<img width="711" alt="Screenshot 2022-11-25 at 14 51 12" src="https://user-images.githubusercontent.com/22298999/203989704-fa875236-d52a-4ed0-aae7-84cbed5afa19.png">

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context

I'm happy to work on a fix if you give me pointers on where to look at. Awesome job, btw ❤️

**Comment by pjkaufman** [comment]
Thanks for pointing this out. It looks like it might be an issue with YAML recognition. I can take a look in a little while.

If you wanted to take a look, I would add the reproducible example into <https://github.com/platers/obsidian-linter/blob/master/__tests__/yaml-title-alias.test.ts> and see if it fails when you run `npm run test-suite yaml-title-alias` . If it does, then you would need to debug the actual logic of the yaml-title alias rule and see what it is not accounting for.

**Comment by pjkaufman** [comment]
I think I gave instructions for the wrong rule above. I am going to take a look and see if I can reproduce this issue.

**Comment by pjkaufman** [comment]
Those definitely were the instructions for the wrong thing. I am trying to reproduce now. I should have a better idea of the cause soon.

**Comment by pjkaufman** [comment]
The proper instructions would be to add a test to <https://github.com/platers/obsidian-linter/blob/master/__tests__/file-name-heading.test.ts> and then run `npm run test-suite file-name-heading`. Then it is a matter of debugging the logic for the actual logic of the rule. I do that using VSCode and its debugging setup for JavaScript files.

**Comment by pjkaufman** [comment]
I believe that I have a fix for this. I am not entirely sure that there should be a blank line between the frontmatter and the header, but as for the header showing up on the same line as the actual frontmatter ending, I have that fixed to where it shows up on the line after it.

**Comment by pjkaufman** [comment]
As for fixing things like this in the future, would it help if I added a section on debugging to <https://github.com/platers/obsidian-linter/blob/master/CONTRIBUTING.md>?

**Comment by alexfertel** [comment]
Hello @pjkaufman ! Thanks for the swift response. 🚀 

> As for fixing things like this in the future, would it help if I added a section on debugging to [master/CONTRIBUTING.md](https://github.com/platers/obsidian-linter/blob/master/CONTRIBUTING.md?rgh-link-date=2022-11-25T14%3A33%3A05Z)?

Ah, I just installed the plugin today and haven't read the [master/CONTRIBUTING.md](https://github.com/platers/obsidian-linter/blob/master/CONTRIBUTING.md?rgh-link-date=2022-11-25T14%3A33%3A05Z) file. I'll report back tomorrow and will let you know if maybe adding a debugging section is helpful.

**Comment by pjkaufman** [comment]
Thanks! I am definitely looking to make the plugin easier to user for other people to contribute. I know it can be kind of tricky with a few things, but I tried to outline several helpful things in the contribution file. Hopefully it explains how to add new rules and fix bugs.

As someone that has helped with this plugin for around 6 months, I assume that I am leaving something out that would be helpful for other people looking to contribute due to my familiarity with the setup of the plugin.

**Comment by pjkaufman** [comment]
This issue should now be fixed on the master branch of the plugin and will go out with the next release. Please let us know if that is not the case.

**Comment by alexfertel** [comment]
Heyo, @pjkaufman. I cloned `master`, built the project locally, and copied the production files to my personal vault and I'm still experiencing the same issue as before.

On closer inspection, it seems to be a combination of issues. After a while of fiddling with the options I noticed that the blank-line after the opening `---` in:

```markdown
---

hello: test
---# Test note
```

is caused by the "All paragraphs should have exactly one blank line both before and after" rule. If I disable this rule, the output is:

```markdown
---
hello: test
---# Test note
```

Note that it still only happens if the only content of the file is the front-matter. If I add something else, the blank-line does not get added.

I'm pasting my `data.json` file here in case it is useful.

```json
{
  "ruleConfigs": {
    "Escape YAML Special Characters": {
      "Escapes colons with a space after them (: ), single quotes ('), and double quotes (\") in YAML.": false,
      "Try to Escape Single Line Arrays": false
    },
    "Force YAML Escape": {
      "Escapes the values for the specified YAML keys.": false,
      "Force YAML Escape on Keys": ""
    },
    "Format Tags in YAML": {
      "Remove Hashtags from tags in the YAML frontmatter, as they make the tags there invalid.": false
    },
    "Format Yaml Array": {
      "Allows for the formatting of regular yaml arrays as either multi-line or single-line and `tags` and `aliases` are allowed to have some Obsidian specific yaml formats. Note that single string to single-line goes from a single string entry to a single-line array if more than 1 entry is present. The same is true for single string to multi-line except it becomes a multi-line array.": false,
      "Format yaml aliases section": true,
      "Format yaml tags section": true,
      "Default yaml array section style": "single-line",
      "Format yaml array sections": true,
      "Force key values to be single-line arrays": "",
      "Force key values to be multi-line arrays": ""
    },
    "Insert YAML attributes": {
      "Inserts the given YAML attributes into the YAML frontmatter. Put each attribute on a single line.": false,
      "Text to insert": "aliases: \ntags: "
    },
    "Move Tags to Yaml": {
      "Move all tags to Yaml frontmatter of the document.": false,
      "Body tag operation": "Nothing",
      "Tags to ignore": ""
    },
    "Remove YAML Keys": {
      "Removes the YAML keys specified": false,
      "YAML Keys to Remove": ""
    },
    "YAML Key Sort": {
      "Sorts the YAML keys based on the order and priority specified. Note: may remove blank lines as well.": false,
      "YAML Key Priority Sort Order": "",
      "Priority Keys at Start of YAML": true,
      "YAML Sort Order for Other Keys": "None"
    },
    "YAML Timestamp": {
      "Keep track of the date the file was last edited in the YAML front matter. Gets dates from file metadata.": false,
      "Date Created": true,
      "Date Created Key": "date created",
      "Date Modified": true,
      "Date Modified Key": "date modified",
      "Format": "dddd, MMMM Do YYYY, h:mm:ss a"
    },
    "YAML Title": {
      "Inserts the title of the file into the YAML frontmatter. Gets the title from the first H1 or filename if there is no H1.": false,
      "Title Key": "title"
    },
    "YAML Title Alias": {
      "Inserts the title of the file into the YAML frontmatter's aliases section. Gets the title from the first H1 or filename.": false,
      "Preserve existing aliases section style": true,
      "Keep alias that matches the filename": false,
      "Use the YAML key `linter-yaml-title-alias` to help with filename and heading changes": true
    },
    "Capitalize Headings": {
      "Headings should be formatted with capitalization": true,
      "Style": "Title Case",
      "Ignore Cased Words": true,
      "Ignore Words": "macOS, iOS, iPhone, iPad, JavaScript, TypeScript, AppleScript",
      "Lowercase Words": "via, a, an, the, and, or, but, for, nor, so, yet, at, by, in, of, on, to, up, as, is, if, it, for, to, with, without, into, onto, per"
    },
    "File Name Heading": {
      "Inserts the file name as a H1 heading if no H1 heading exists.": true
    },
    "Header Increment": {
      "Heading levels should only increment by one level at a time": true
    },
    "Footnote after Punctuation": {
      "Ensures that footnote references are placed after punctuation, not before.": true
    },
    "Move Footnotes to the bottom": {
      "Move all footnotes to the bottom of the document.": true
    },
    "Re-Index Footnotes": {
      "Re-indexes footnote keys and footnote, based on the order of occurrence (NOTE: This rule deliberately does *not* preserve the relation between key and footnote, to be able to re-index duplicate keys.)": true
    },
    "Convert Bullet List Markers": {
      "Converts common bullet list marker symbols to markdown list markers.": true
    },
    "Emphasis Style": {
      "Makes sure the emphasis style is consistent.": true,
      "Style": "asterisk"
    },
    "No Bare URLs": {
      "Encloses bare URLs with angle brackets except when enclosed in back ticks, square braces, or single or double quotes.": true
    },
    "Ordered List Style": {
      "Makes sure that ordered lists follow the style specified. Note that 2 spaces or 1 tab is considered to be an indentation level.": false,
      "Number Style": "ascending",
      "Ordered List Indicator End Style": "."
    },
    "Proper Ellipsis": {
      "Replaces three consecutive dots with an ellipsis.": false
    },
    "Remove Consecutive List Markers": {
      "Removes consecutive list markers. Useful when copy-pasting list items.": false
    },
    "Remove Empty List Markers": {
      "Removes empty list markers, i.e. list items without content.": false
    },
    "Remove Hyphenated Line Breaks": {
      "Removes hyphenated line breaks. Useful when pasting text from textbooks.": true
    },
    "Remove Multiple Spaces": {
      "Removes two or more consecutive spaces. Ignores spaces at the beginning and ending of the line. ": true
    },
    "Strong Style": {
      "Makes sure the strong style is consistent.": true,
      "Style": "asterisk"
    },
    "Two Spaces Between Lines with Content": {
      "Makes sure that two spaces are added to the ends of lines with content continued on the next line for paragraphs, blockquotes, and list items": true
    },
    "Unordered List Style": {
      "Makes sure that unordered lists follow the style specified.": true,
      "List item style": "-"
    },
    "Compact YAML": {
      "Removes leading and trailing blank lines in the YAML front matter.": true,
      "Inner New Lines": true
    },
    "Consecutive blank lines": {
      "There should be at most one consecutive blank line.": true
    },
    "Convert Spaces to Tabs": {
      "Converts leading spaces to tabs.": false,
      "Tabsize": 4
    },
    "Empty Line Around Blockquotes": {
      "Ensures that there is an empty line around blockquotes unless they start or end a document. **Note that an empty line is either one less level of nesting for blockquotes or a newline character.**": true
    },
    "Empty Line Around Code Fences": {
      "Ensures that there is an empty line around code fences unless they start or end a document.": false
    },
    "Empty Line Around Math Blocks": {
      "Ensures that there is an empty line around math blocks using `Number of Dollar Signs to Indicate a Math Block` to determine how many dollar signs indicates a math block for single-line math.": false
    },
    "Empty Line Around Tables": {
      "Ensures that there is an empty line around github flavored tables unless they start or end a document.": true
    },
    "Heading blank lines": {
      "All headings have a blank line both before and after (except where the heading is at the beginning or end of the document).": false,
      "Bottom": false,
      "Empty Line Between Yaml and Header": false
    },
    "Line Break at Document End": {
      "Ensures that there is exactly one line break at the end of a document.": true
    },
    "Move Math Block Indicators to Their Own Line": {
      "Move all starting and ending math block indicators to their own lines using `Number of Dollar Signs to Indicate a Math Block` to determine how many dollar signs indicates a math block for single-line math.": false
    },
    "Paragraph blank lines": {
      "All paragraphs should have exactly one blank line both before and after.": false
    },
    "Remove Empty Lines Between List Markers and Checklists": {
      "There should not be any empty lines between list markers and checklists.": true
    },
    "Remove link spacing": {
      "Removes spacing around link text.": true
    },
    "Remove Space around Fullwidth Characters": {
      "Ensures that fullwidth characters are not followed by whitespace (either single spaces or a tab). Note that this may causes issues with markdown format in some cases.": false
    },
    "Space after list markers": {
      "There should be a single space after list markers and checkboxes.": true
    },
    "Space between Chinese Japanese or Korean and English or numbers": {
      "Ensures that Chinese, Japanese, or Korean and English or numbers are separated by a single space. Follows these [guidelines](https://github.com/sparanoid/chinese-copywriting-guidelines)": true
    },
    "Trailing spaces": {
      "Removes extra spaces after every line.": true,
      "Two Space Linebreak": true
    },
    "Add Blockquote Indentation on Paste": {
      "Adds blockquotes to all but the first line, when the cursor is in a blockquote/callout line during pasting": true
    },
    "Prevent Double Checklist Indicator on Paste": {
      "Removes starting checklist indicator from the text to paste if the line the cursor is on in the file has a checklist indicator": false
    },
    "Prevent Double List Item Indicator on Paste": {
      "Removes starting list indicator from the text to paste if the line the cursor is on in the file has a list indicator": false
    },
    "Proper Ellipsis on Paste": {
      "Replaces three consecutive dots with an ellipsis even if they have a space between them in the text to paste": false
    },
    "Remove Hyphens on Paste": {
      "Removes hyphens from the text to paste": true
    },
    "Remove Leading or Trailing Whitespace on Paste": {
      "Removes any leading non-tab whitespace and all trailing whitespace for the text to paste": false
    },
    "Remove Leftover Footnotes from Quote on Paste": {
      "Removes any leftover footnote references for the text to paste": false
    },
    "Remove Multiple Blank Lines on Paste": {
      "Condenses multiple blank lines down into one blank line for the text to paste": false
    }
  },
  "lintOnSave": true,
  "displayChanged": false,
  "foldersToIgnore": [
    ".obsidian",
    "archive",
    "templates",
    "scripts"
  ],
  "linterLocale": "system-default",
  "logLevel": 4,
  "lintCommands": [],
  "customRegexes": [],
  "commonStyles": {
    "aliasArrayStyle": "single-line",
    "tagArrayStyle": "single-line",
    "minimumNumberOfDollarSignsToBeAMathBlock": 2,
    "escapeCharacter": "\""
  }
}
```

Maybe we can reopen the issue?

**Comment by pjkaufman** [comment]
That's odd. It should be ignoring the YAML. But maybe it is not. Some of the rules definitely do not play well together. I will see if I can reproduce with the `data.json` you provided.

**Comment by alexfertel** [comment]
Update: it seems that it is the combination of both rules. If I disable the "Inserts the file name as a H1 heading if no H1 heading exists." rule, then the other one works fine!

**Comment by alexfertel** [comment]
Yeah, the apply of the `paragraph-blank-lines` rule is:

```typescript
  apply(text: string, options: ParagraphBlankLinesOptions): string {
    return ignoreListOfTypes([IgnoreTypes.obsidianMultiLineComments, IgnoreTypes.yaml, IgnoreTypes.table], text, makeSureThereIsOnlyOneBlankLineBeforeAndAfterParagraphs);
  }
```

And the regex for yaml `const yamlRegex = /^---\n((?:(((?!---)(?:.|\n)*?)\n)?))---(?=\n|$)/` expects the yaml block to end in `\n` or `$`. It seems that the `file-name-heading` rule gets applied first, so after it gets applied, the note is this:

```markdown
---
hello: test
---# Test note
```

Which means that it is not considered a yaml block anymore by and it doesn't get ignored, so the blank-line gets inserted.

**Comment by alexfertel** [comment]
This means that fixing the `file-name-heading` rule, should fix the other one as well.

**Comment by alexfertel** [comment]
@pjkaufman nevermind I found the problem! I had to restart obsidian for the update to take effect. The plugin didn't get reloaded. It works fine now 👍🏻

**Comment by pjkaufman** [comment]
Oh good. I was a bit worried this would need to deal with interrule issues.
