### ISSUE TITLE
Bug: Setting Error after Update 1.10.0

### ISSUE THREAD

**Issue by Liong1976** [platers/obsidian-linter#564]
## Describe the Bug

After I installed the 1.10,0 version, the Setting configuration for Linter messed up

## How to Reproduce

1. Update to 1,10,0
2. Open Setting (Ctrl+P)
3. Find Linter in the Setting

## Expected Behavior

Just showing `Linter` in the Setting Menu

## Screenshots

![image](https://user-images.githubusercontent.com/88898230/209052997-ca88ca02-65c2-4e40-9d50-7345cd6484dd.png)

## Device

- [X] Desktop
- [ ] Mobile

## Additional Context

Windows 10; Obsidian 1.18.0

**Comment by pjkaufman** [comment]
@Liong1976 , are there any errors in the console or are you making the screen intentionally smaller than your normal screen size? I am not able to reproduce the issue on my device.

Is this something you are seeing every time you open the Linter settings? Also, does it continue to happen if you kill Obsidian and start again?

**Comment by Liong1976** [comment]
Hi @pjkaufman,
I restarted Obsidian, and there was no change. However, after reading your message, I tried to restart the Obsidian again, and it was back to normal.

Sorry for bothering you.

**Comment by pjkaufman** [comment]
No worries. I am glad to here that it is fixed. I will go ahead and close this.

**Comment by Liong1976** [comment]
I don't know why the issue happened again. I saw the console and found no error in it. I restarted Obsidian several times, and the problem persisted. 

It happened even when I didn't open the Linter plugin. I just opened Setting.

**Comment by pjkaufman** [comment]
Gotcha. This is similar to another issue reported (#565 ). I am making changes there. It seems I added some logic that directly overlaps with the what Obsidian uses. This causes the conflict. In creating the fix, I noticed some slowness on plugin setting load (about 7 seconds), so I am working to fix that now.
