### ISSUE TITLE
Bug: YAML Key Sort doesn't support some YAML syntax

### ISSUE THREAD

**Issue by redactedscribe** [platers/obsidian-linter#912]
- [x] I have verified that I am on the latest version of the Linter

Apologies if this issue has already been created. Not quite sure what to search for.

## Describe the Bug

According to https://www.yamllint.com/, this is valid:

```yaml
---
AAA:
  - BBB: x
    CCC: x
  - DDD: x
    EEE: x
    FFF:
      - GGG: x
      - HHH
    III: x
FFF:
  -
```

`FFF` is present twice, but at different levels, and therefore should be unique, but obsidian-linter still complains with (even if line with `GGG` has `: x` removed):

```
plugin:obsidian-linter:43 [Obsidian Linter] Lint File Error in File 'Test.md':
Error "YAML Key Sort" encountered an error in the YAML:  bad indentation of a sequence entry (35:8)

 32 |     FFF:
 33 |   - GGG: x
 34 |   - HHH
 35 |     III: x
-------------^
 36 | FFF:
 37 |   - 
YAMLException: bad indentation of a sequence entry (35:8)

 32 |     FFF:
 33 |   - GGG: x
 34 |   - HHH
 35 |     III: x
-------------^
 36 | FFF:
 37 |   - 
    at Cc (plugin:obsidian-linter:18:944)
    at K (plugin:obsidian-linter:18:978)
    at dc (plugin:obsidian-linter:25:696)
    at Wt (plugin:obsidian-linter:25:4861)
    at Og (plugin:obsidian-linter:25:2150)
    at Wt (plugin:obsidian-linter:25:4870)
    at Ig (plugin:obsidian-linter:25:7247)
    at Mc (plugin:obsidian-linter:26:258)
    at Fg (plugin:obsidian-linter:26:469)
    at Mi (plugin:obsidian-linter:104:223)
Uc @ plugin:obsidian-linter:43
```

## How to Reproduce

1. Insert the front matter above into a file.
2. Lint with YAML Key Sort enabled (screenshot below for settings).

## Expected Behavior

Support this YAML syntax.

## Screenshots

![Obsidian_2023-10-11_00-21-34](https://github.com/platers/obsidian-linter/assets/25013746/5fd549b7-c613-425a-aba0-1c09de1d163a)

## Device

- [x] Desktop
- [ ] Mobile

Thanks.

**Comment by redactedscribe** [comment]
Other observations:

- Adding a value (i.e. even just `:`) to `HHH` key causes the YAML to lint, but it merges `FFF` together at the root level (and also erroneously the `III` key too).
- After adding a value to `HHH` and then removing the leading `-` from both `GGG` and `HHH` causes `FFF` keys to merge and `GGG` and `HHH` to be deleted (with `III` also merged).

Technically, the above doesn't happen with the example code in the first comment, but it's what I'm seeing happen with my real-world example because my `FFF` so-to-speak is earlier in the alphabet than the `AAA`. The reason seems to be because of the YAML Sort Order for Other Keys setting being set to Ascending Alphabetical.

```
---
AAA:
  - BBB: x
    CCC: x
  - DDD: x
    EEE: x
    A:
      - GGG: x
      - HHH: 
    III: x
A:
  -
---
```

... linted turns into:

```
---
A:
  - GGG: x
  - HHH: 
    III: x
AAA:
  - BBB: x
    CCC: x
  - DDD: x
    EEE: x
---
```

This bug report is a bit of a mess, sorry. Hopefully you can make sense of it.

**Comment by pjkaufman** [comment]
If this is an issue with the YAML after the Linter runs, I can do something about it. Jowever if this is from the parser, I cannot do anything about that at this time.

**Comment by redactedscribe** [comment]
I believe the linter is the cause as I'm manually triggering linting using Ctrl+Alt+L.

**Comment by pjkaufman** [comment]
It says there is bad indentation. Is the YAML line it is referring to the same as the initial value? If so, there may be nothing I can do. Generally bad identation means it was expecting more or less spaces than were provided.

**Comment by pjkaufman** [comment]
The error provided seems to happen before YAML Key Sort happens. That would mean I likely cannot fix it via the Linter code since it is an external library that parses the YAML.

**Comment by pjkaufman** [comment]
YAML Key Sort definitely needs work. It was a workaround to get it to work, but it cannot handle nesting due to its implementation. It would have to be rewritten to handle sorting nested values. However if it is pulling nested values out of their nesting level, that may ne addressable.

**Comment by redactedscribe** [comment]
> However if it is pulling nested values out of their nesting level, that may ne addressable.

That it is doing, and at times removing them without them even being merged.

**Comment by pjkaufman** [comment]
I will need to double check what modified this. I am able to reproduce in Obsidian, but YAML Key Sort does not seem to affect this directly. Some other rule seems to be modifying it first which is causing the issue. I will have to see which rule is making that change and make the modification in that rule.

**Comment by mariomui** [comment]
@pjkaufman Do you want me to work on this? cuz there's overlap with my sort frontmatter, i just dont test on mobile so i'll need some help on that front.

**Comment by pjkaufman** [comment]
Hey @mariomui , that would be great. I can test mobile, so that should not be an issue.

**Comment by pjkaufman** [comment]
My main concern would be avoiding breaking existing UTs and keeping the original formatting as much as possible, but the latter is more lenient.

**Comment by pjkaufman** [comment]
I have merged a change that should fix this. It may cause other issues, so I plan to put this out as beta release that will hopefully help us determine any issues that exist prior to having it roll out to all users.

**Comment by breakid** [comment]
Using the latest version of Obsidian (v1.8.10) and the latest version of the Linter plugin (v1.29.0), I'm still not able to successfully lint the original example. I'm not sure whether it's the same bug or a new bug; I'm happy to submit a separate issue if you prefer.

Specifically, linting the original example:

```yaml
---
AAA:
  - BBB: x
    CCC: x
  - DDD: x
    EEE: x
    FFF:
      - GGG: x
      - HHH
    III: x
FFF:
  -
```

results in a new error:

```
Error "Insert YAML attributes" encountered an unknown error: Implicit keys need to be on a single line at line 17, column 5:

  - HHH
    ^

YAMLParseError: Implicit keys need to be on a single line at line 17, column 5:

  - HHH
    ^

    at Vs.onError (plugin:obsidian-linter:181:350)
    at Eh (plugin:obsidian-linter:143:72)
    at Ld (plugin:obsidian-linter:148:153)
    at Oh (plugin:obsidian-linter:148:765)
    at xd (plugin:obsidian-linter:178:2369)
    at xh (plugin:obsidian-linter:144:763)
    at Ld (plugin:obsidian-linter:148:188)
    at Oh (plugin:obsidian-linter:148:765)
    at xd (plugin:obsidian-linter:178:2369)
    at Eh (plugin:obsidian-linter:143:852)
Ma	@	plugin:obsidian-linter:12
```

If I add a trailing `:` to `- HHH` (which isn't required for valid YAML), the linter will run but generate the following incorrect output:

```
AAA:
  - BBB: x
    CCC: x
  - DDD: x
    EEE: x
    FFF:
  - GGG: x
  - HHH:
    III: x
FFF:
  -
```

While `- GGG` and `- HHH` are no longer grouped at the root level, as in the original report, they are still not properly indented beneath `FFF:`. This also affects `III:`, which is now part of a separate dictionary with `HHH:`.

**Comment by pjkaufman** [comment]
@breakid,  could you provide your `data.json` file? I was able to lint the original logic using just the rule referenced by the original ticket. So unless something changed or I did the teats wrong, this may be caused by multiple rules running and I want to rule that out.

**Comment by breakid** [comment]
My apologies, the notification for your response got buried in my inbox.

Here is the contents of my `data.json` file:

```json
{
  "ruleConfigs": {
    "Remove Space around Fullwidth Characters": {
      "Ensures that fullwidth characters are not followed by whitespace (either single spaces or a tab). Note that this may causes issues with markdown format in some cases.": false
    },
    "escape-yaml-special-characters": {
      "enabled": false,
      "try-to-escape-single-line-arrays": false
    },
    "force-yaml-escape": {
      "enabled": false,
      "force-yaml-escape-keys": ""
    },
    "format-tags-in-yaml": {
      "enabled": false
    },
    "format-yaml-array": {
      "enabled": true,
      "alias-key": true,
      "tag-key": true,
      "default-array-style": "multi-line",
      "default-array-keys": true,
      "force-single-line-array-style": "",
      "force-multi-line-array-style": "aliases\nattendees\ncategories\ngenres\ntags\nnext_actions\nhistory\nimported_tags"
    },
    "insert-yaml-attributes": {
      "enabled": true,
      "text-to-insert": "note_creator: "
    },
    "move-tags-to-yaml": {
      "enabled": false,
      "how-to-handle-existing-tags": "Nothing",
      "tags-to-ignore": ""
    },
    "remove-yaml-keys": {
      "enabled": false,
      "yaml-keys-to-remove": ""
    },
    "yaml-key-sort": {
      "enabled": true,
      "yaml-key-priority-sort-order": "note_creator\ncreated\nupdated\npublish\ntype\nschema\ntitle\nfilename\nname\naliases\ncomment\ndescription\ndescription_raw\nimage\nid\nrawg_id\nsteam_id\nisbn10\nisbn13\ncollections\nurl\nurl_source_code\nurl_documentation\nurl_chrome_extension\nurl_firefox_addon\nurl_marketplace\nurl_pypi\nsource_code_url\ndocumentation_url\nchrome_extension_url\nfirefox_addon_url\nmarketplace_url\npaths\ncreator\ndeveloper\nartist\nauthor\nstudios\nnarrator\npublisher\nproducers\nactors\nrelease_date\ndate\nyear\ntime\nlength\nlength_raw\nlocation\nlead\nattendees\ncategories\ngenres\ntheme\nnum_parts\nesrb_rating\nrating\nrating_personal\npersonal_rating\nstatus\nreason\nconsulted\nimportance\nurgency\nlevel_of_effort\ndue_date\ntags\nimported_tags\nnext_actions\npurchased\nhistory\nwatch_history\nsummary\nbookmarks\npros\ncons\nuse_cases\ninstructions_installation\ninstructions_configuration\ninstructions_usage\ntroubleshooting\nproposed_improvements\nnotes\nrelated_notes\nexternal_resources",
      "priority-keys-at-start-of-yaml": true,
      "yaml-sort-order-for-other-keys": "Ascending Alphabetical"
    },
    "yaml-timestamp": {
      "enabled": true,
      "date-created": true,
      "date-created-key": "created",
      "date-modified": true,
      "date-modified-key": "updated",
      "format": "YYYY-MM-DD HH:mm:ss",
      "date-created-source-of-truth": "frontmatter",
      "date-modified-source-of-truth": "user or Linter edits",
      "convert-to-utc": false,
      "update-on-file-contents-updated": "never"
    },
    "yaml-title": {
      "enabled": false,
      "title-key": "title",
      "mode": "first-h1"
    },
    "yaml-title-alias": {
      "enabled": true,
      "preserve-existing-alias-section-style": true,
      "keep-alias-that-matches-the-filename": false,
      "use-yaml-key-to-keep-track-of-old-filename-or-heading": false,
      "alias-helper-key": "linter-yaml-title-alias"
    },
    "capitalize-headings": {
      "enabled": false,
      "style": "Title Case",
      "ignore-case-words": true,
      "ignore-words": "macOS, iOS, iPhone, iPad, JavaScript, TypeScript, AppleScript",
      "lowercase-words": "via, a, an, the, and, or, but, for, nor, so, yet, at, by, in, of, on, to, up, as, is, if, it, for, to, with, without, into, onto, per"
    },
    "file-name-heading": {
      "enabled": false
    },
    "header-increment": {
      "enabled": true,
      "start-at-h2": false
    },
    "footnote-after-punctuation": {
      "enabled": true
    },
    "move-footnotes-to-the-bottom": {
      "enabled": true
    },
    "re-index-footnotes": {
      "enabled": true
    },
    "convert-bullet-list-markers": {
      "enabled": true
    },
    "emphasis-style": {
      "enabled": true,
      "style": "underscore"
    },
    "no-bare-urls": {
      "enabled": false,
      "no-bare-uris": false
    },
    "ordered-list-style": {
      "enabled": true,
      "number-style": "ascending",
      "list-end-style": "."
    },
    "proper-ellipsis": {
      "enabled": false
    },
    "remove-consecutive-list-markers": {
      "enabled": true
    },
    "remove-empty-list-markers": {
      "enabled": true
    },
    "remove-hyphenated-line-breaks": {
      "enabled": true
    },
    "remove-multiple-spaces": {
      "enabled": true
    },
    "strong-style": {
      "enabled": true,
      "style": "asterisk"
    },
    "two-spaces-between-lines-with-content": {
      "enabled": false,
      "line-break-indicator": "  "
    },
    "unordered-list-style": {
      "enabled": true,
      "list-style": "-"
    },
    "compact-yaml": {
      "enabled": true,
      "inner-new-lines": false
    },
    "consecutive-blank-lines": {
      "enabled": true
    },
    "convert-spaces-to-tabs": {
      "enabled": false,
      "tabsize": "4"
    },
    "empty-line-around-blockquotes": {
      "enabled": true
    },
    "empty-line-around-code-fences": {
      "enabled": true
    },
    "empty-line-around-math-blocks": {
      "enabled": true
    },
    "empty-line-around-tables": {
      "enabled": true
    },
    "heading-blank-lines": {
      "enabled": true,
      "bottom": true,
      "empty-line-after-yaml": true
    },
    "line-break-at-document-end": {
      "enabled": true
    },
    "move-math-block-indicators-to-their-own-line": {
      "enabled": false
    },
    "paragraph-blank-lines": {
      "enabled": false
    },
    "remove-empty-lines-between-list-markers-and-checklists": {
      "enabled": true
    },
    "remove-link-spacing": {
      "enabled": true
    },
    "space-after-list-markers": {
      "enabled": true
    },
    "space-between-chinese-japanese-or-korean-and-english-or-numbers": {
      "enabled": false,
      "english-symbols-punctuation-before": "-+;:'\"°%$)]",
      "english-symbols-punctuation-after": "-+'\"([¥$"
    },
    "trailing-spaces": {
      "enabled": true,
      "twp-space-line-break": false
    },
    "add-blockquote-indentation-on-paste": {
      "enabled": false
    },
    "prevent-double-checklist-indicator-on-paste": {
      "enabled": false
    },
    "prevent-double-list-item-indicator-on-paste": {
      "enabled": false
    },
    "proper-ellipsis-on-paste": {
      "enabled": false
    },
    "remove-hyphens-on-paste": {
      "enabled": false
    },
    "remove-leading-or-trailing-whitespace-on-paste": {
      "enabled": false
    },
    "remove-leftover-footnotes-from-quote-on-paste": {
      "enabled": false
    },
    "remove-multiple-blank-lines-on-paste": {
      "enabled": false
    },
    "headings-start-line": {
      "enabled": true
    },
    "remove-trailing-punctuation-in-heading": {
      "enabled": true,
      "punctuation-to-remove": ".,;:!。，；：！"
    },
    "auto-correct-common-misspellings": {
      "enabled": false,
      "ignore-words": "",
      "skip-words-with-multiple-capitals": false,
      "extra-auto-correct-files": []
    },
    "blockquote-style": {
      "enabled": true,
      "style": "space"
    },
    "quote-style": {
      "enabled": true,
      "single-quote-enabled": true,
      "single-quote-style": "''",
      "double-quote-enabled": true,
      "double-quote-style": "\"\""
    },
    "remove-space-around-characters": {
      "enabled": false,
      "include-fullwidth-forms": true,
      "include-cjk-symbols-and-punctuation": true,
      "include-dashes": false,
      "other-symbols": ""
    },
    "remove-space-before-or-after-characters": {
      "enabled": false,
      "characters-to-remove-space-before": ",!?;:).’”]",
      "characters-to-remove-space-after": "¿¡‘“(["
    },
    "add-blank-line-after-yaml": {
      "enabled": true
    },
    "default-language-for-code-fences": {
      "enabled": false,
      "default-language": ""
    },
    "dedupe-yaml-array-values": {
      "enabled": true,
      "dedupe-alias-key": true,
      "dedupe-tag-key": true,
      "dedupe-array-keys": false,
      "ignore-keys": ""
    },
    "sort-yaml-array-values": {
      "enabled": true,
      "sort-alias-key": true,
      "sort-tag-key": true,
      "sort-array-keys": true,
      "ignore-keys": "next_actions\nuse_cases",
      "sort-order": "Ascending Alphabetical"
    },
    "empty-line-around-horizontal-rules": {
      "enabled": true
    }
  },
  "lintOnSave": true,
  "recordLintOnSaveLogs": false,
  "displayChanged": true,
  "lintOnFileChange": true,
  "displayLintOnFileChangeNotice": false,
  "settingsConvertedToConfigKeyValues": true,
  "foldersToIgnore": [
    "_Inbox",
    "_utils"
  ],
  "filesToIgnore": [],
  "linterLocale": "system-default",
  "logLevel": "ERROR",
  "lintCommands": [],
  "customRegexes": [],
  "commonStyles": {
    "aliasArrayStyle": "multi-line",
    "tagArrayStyle": "multi-line",
    "minimumNumberOfDollarSignsToBeAMathBlock": 2,
    "escapeCharacter": "\"",
    "removeUnnecessaryEscapeCharsForMultiLineArrays": true
  }
}
```

**Comment by pjkaufman** [comment]
I believe I have a fix for this. I am not sure what exactly the issue was, but with a change that was made recently this seems to be fixed. So it should be fixed in the next release.

**Comment by pjkaufman** [comment]
I have merged the change for this into master. It should go out in the next release. Please let us know if the issue still persists.
